const express=require("express"),helmet=require("helmet"),rateLimit=require("express-rate-limit"),crypto=require("crypto"),db=require("./db"),path=require("path");
const app=express(),PORT=Number(process.env.PORT||3000),SECRET=process.env.SESSION_SECRET||"dev-only-change-me";
app.set("trust proxy",1);app.use(helmet({crossOriginResourcePolicy:false}));app.use(express.json({limit:"32kb"}));app.use(express.urlencoded({extended:false}));app.use(rateLimit({windowMs:900000,limit:300,standardHeaders:true}));app.use(express.static("public"));
function clean(v,n){return String(v??"").trim().slice(0,n)}
function hash(p){const s=crypto.randomBytes(16),h=crypto.pbkdf2Sync(p,s,210000,32,"sha256");return s.toString("base64")+":"+h.toString("base64")}
function verify(p,x){try{const[a,b]=x.split(":"),s=Buffer.from(a,"base64"),e=Buffer.from(b,"base64"),h=crypto.pbkdf2Sync(p,s,210000,32,"sha256");return e.length===h.length&&crypto.timingSafeEqual(e,h)}catch{return false}}
function token(id){const d=id+"."+Date.now(),sig=crypto.createHmac("sha256",SECRET).update(d).digest("hex");return Buffer.from(d+"."+sig).toString("base64url")}
function userFrom(req){try{const r=Buffer.from(String(req.headers.authorization||"").replace(/^Bearer\s+/i,""),"base64url").toString().split("."),d=r[0]+"."+r[1],e=crypto.createHmac("sha256",SECRET).update(d).digest("hex");if(r.length!==3||!crypto.timingSafeEqual(Buffer.from(r[2]),Buffer.from(e))||Date.now()-Number(r[1])>1209600000)return null;return db.prepare("SELECT id,nickname,email,age,bio FROM users WHERE id=?").get(Number(r[0]))||null}catch{return null}}
function auth(req,res,next){req.user=userFrom(req);if(!req.user)return res.status(401).json({error:"ログインが必要です"});next()}
function blocked(a,b){return !!db.prepare("SELECT 1 FROM blocks WHERE (blocker=? AND blocked=?) OR (blocker=? AND blocked=?)").get(a,b,b,a)}
function matched(a,b){return !!db.prepare("SELECT 1 FROM likes x JOIN likes y ON x.to_user=y.from_user AND x.from_user=y.to_user WHERE x.from_user=? AND x.to_user=?").get(a,b)}

app.get("/api/me",auth,(q,s)=>s.json({user:q.user}));
app.post("/api/register",(q,s)=>{const n=clean(q.body.nickname,30),e=clean(q.body.email,120).toLowerCase(),p=String(q.body.password||""),a=Number(q.body.age);if(!n||!e.includes("@")||p.length<8||!Number.isInteger(a)||a<18)return s.status(400).json({error:"18歳以上・8文字以上のパスワードなど入力を確認してください"});try{const x=db.prepare("INSERT INTO users(nickname,email,password_hash,age,bio) VALUES(?,?,?,?,?)").run(n,e,hash(p),a,clean(q.body.bio,500));s.json({token:token(x.lastInsertRowid)})}catch(e){s.status(409).json({error:"そのメールアドレスは登録済みです"})}});
app.post("/api/login",(q,s)=>{const e=clean(q.body.email,120).toLowerCase(),p=String(q.body.password||""),u=db.prepare("SELECT * FROM users WHERE email=?").get(e);if(!u||!verify(p,u.password_hash))return s.status(401).json({error:"メールアドレスまたはパスワードが違います"});s.json({token:token(u.id)})});
app.put("/api/profile",auth,(q,s)=>{const n=clean(q.body.nickname,30),a=Number(q.body.age);if(!n||!Number.isInteger(a)||a<18)return s.status(400).json({error:"プロフィールを確認してください"});db.prepare("UPDATE users SET nickname=?,age=?,bio=? WHERE id=?").run(n,a,clean(q.body.bio,500),q.user.id);s.json({ok:true})});
app.get("/api/users",auth,(q,s)=>{const x=clean(q.query.q,50),min=Math.max(18,Number(q.query.minAge)||18),max=Math.min(120,Number(q.query.maxAge)||120);s.json({users:db.prepare(`SELECT id,nickname,age,bio FROM users WHERE id<>? AND age BETWEEN ? AND ? AND id NOT IN(SELECT blocked FROM blocks WHERE blocker=?) AND id NOT IN(SELECT blocker FROM blocks WHERE blocked=?) AND(nickname LIKE ? OR bio LIKE ?) ORDER BY id DESC LIMIT 100`).all(q.user.id,min,max,q.user.id,q.user.id,"%"+x+"%","%"+x+"%")})});
app.post("/api/like/:id",auth,(q,s)=>{const b=Number(q.params.id);if(!b||b===q.user.id||blocked(q.user.id,b))return s.status(400).json({error:"いいねできません"});if(!db.prepare("SELECT id FROM users WHERE id=?").get(b))return s.status(404).json({error:"ユーザーが見つかりません"});db.prepare("INSERT OR IGNORE INTO likes VALUES(?,?,CURRENT_TIMESTAMP)").run(q.user.id,b);s.json({matched:matched(q.user.id,b)})});
app.get("/api/matches",auth,(q,s)=>s.json({matches:db.prepare(`SELECT u.id,u.nickname,u.age,u.bio FROM users u WHERE u.id IN(SELECT x.to_user FROM likes x JOIN likes y ON x.to_user=y.from_user AND x.from_user=y.to_user WHERE x.from_user=?) AND u.id NOT IN(SELECT blocked FROM blocks WHERE blocker=?) AND u.id NOT IN(SELECT blocker FROM blocks WHERE blocked=?)`).all(q.user.id,q.user.id,q.user.id)}));
app.get("/api/messages/:id",auth,(q,s)=>{const b=Number(q.params.id);if(!matched(q.user.id,b)||blocked(q.user.id,b))return s.status(403).json({error:"マッチ相手のみ利用できます"});s.json({messages:db.prepare(`SELECT id,sender,receiver,body,created_at FROM messages WHERE(sender=? AND receiver=?)OR(sender=? AND receiver=?) ORDER BY id ASC LIMIT 200`).all(q.user.id,b,b,q.user.id)})});
app.post("/api/messages/:id",auth,(q,s)=>{const b=Number(q.params.id),body=clean(q.body.body,1000);if(!body||!matched(q.user.id,b)||blocked(q.user.id,b))return s.status(400).json({error:"送信できません"});db.prepare("INSERT INTO messages(sender,receiver,body) VALUES(?,?,?)").run(q.user.id,b,body);s.json({ok:true})});
app.post("/api/block/:id",auth,(q,s)=>{const b=Number(q.params.id);if(!b||b===q.user.id)return s.status(400).json({error:"ブロックできません"});db.prepare("INSERT OR IGNORE INTO blocks VALUES(?,?,CURRENT_TIMESTAMP)").run(q.user.id,b);s.json({ok:true})});
app.post("/api/report/:id",auth,(q,s)=>{const b=Number(q.params.id),r=clean(q.body.reason,500);if(!b||b===q.user.id||!r)return s.status(400).json({error:"通報理由を入力してください"});db.prepare("INSERT INTO reports(reporter,target,reason) VALUES(?,?,?)").run(q.user.id,b,r);s.json({ok:true})});
app.get("*",(q,s)=>q.path.startsWith("/api/")?s.status(404).json({error:"Not found"}):s.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log("まこマッチ running on "+PORT));